name: 05 - 1 - Event filters and Acivity Types

on:
    pull_request:
        types:
            - opened
            - synchronize
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Runing whenever a PR is opened or synchronized AND basebranch is main"            