name: 05 - 2 - Event filters and Acivity Types

on:
    pull_request:
        types:
            - closed
        branches:
            - main

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Runing whenever a PR is closed"            